"""model changes

Revision ID: 8bc085298eee
Revises: ad6096532df5
Create Date: 2026-08-14 12:03:27.937420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bc085298eee'
down_revision: Union[str, Sequence[str], None] = 'ad6096532df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_action_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('purpose', sa.Enum('password_reset', 'email_verification', name='authactiontokenpurpose'), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_auth_action_tokens_organization_id_organizations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_action_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_action_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_action_tokens_token_hash'))
    )
    op.create_index('ix_auth_action_tokens_org_purpose_created_at', 'auth_action_tokens', ['organization_id', 'purpose', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_auth_action_tokens_purpose_expires_at', 'auth_action_tokens', ['purpose', 'expires_at'], unique=False)
    op.create_index('ix_auth_action_tokens_token_hash', 'auth_action_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_auth_action_tokens_user_id'), 'auth_action_tokens', ['user_id'], unique=False)
    op.create_index('ix_auth_action_tokens_user_purpose', 'auth_action_tokens', ['user_id', 'purpose'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_action_tokens_user_purpose', table_name='auth_action_tokens')
    op.drop_index(op.f('ix_auth_action_tokens_user_id'), table_name='auth_action_tokens')
    op.drop_index('ix_auth_action_tokens_token_hash', table_name='auth_action_tokens')
    op.drop_index('ix_auth_action_tokens_purpose_expires_at', table_name='auth_action_tokens')
    op.drop_index('ix_auth_action_tokens_org_purpose_created_at', table_name='auth_action_tokens')
    op.drop_table('auth_action_tokens')
    # ### end Alembic commands ###
