"""Initial schema test01

Revision ID: a3843fa1d174
Revises: ad6096532df5
Create Date: 2026-08-07 10:49:27.251479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3843fa1d174'
down_revision: Union[str, Sequence[str], None] = 'ad6096532df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_api_keys_key_hash'), 'api_keys', ['key_hash'])
    op.create_unique_constraint(op.f('uq_attendance_qr_tokens_token'), 'attendance_qr_tokens', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_attendance_qr_tokens_token'), 'attendance_qr_tokens', type_='unique')
    op.drop_constraint(op.f('uq_api_keys_key_hash'), 'api_keys', type_='unique')
    # ### end Alembic commands ###
